# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/soham/Downloads/newton_law_of_cooling/hls_component/hls_component/hls/impl/verilog/solveCooling.xdc

# Block Designs: bd/bd_0/bd_0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0 || ORIG_REF_NAME==bd_0} -quiet] -quiet

# IP: bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0_hls_inst_0 || ORIG_REF_NAME==bd_0_hls_inst_0} -quiet] -quiet

# XDC: /home/soham/Downloads/newton_law_of_cooling/hls_component/hls_component/hls/impl/verilog/project.gen/sources_1/bd/bd_0/bd_0_ooc.xdc
