#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Feb 26 21:40:10 IST 2024
# SW Build 4126759 on Thu Feb  8 23:52:05 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim bd_0_wrapper_time_impl -key {Post-Implementation:sim_1:Timing:bd_0_wrapper} -tclbatch bd_0_wrapper.tcl -protoinst "protoinst_files/bd_0.protoinst" -log simulate.log"
xsim bd_0_wrapper_time_impl -key {Post-Implementation:sim_1:Timing:bd_0_wrapper} -tclbatch bd_0_wrapper.tcl -protoinst "protoinst_files/bd_0.protoinst" -log simulate.log

